/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyCookiePolicyRouteImport } from './routes/privacy-cookie-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiEnquiryRouteImport } from './routes/api.enquiry'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as Blog20ProductSamplingIdeasRouteImport } from './routes/blog.20-product-sampling-ideas'
import { Route as BlogWhatIsProductSamplingRouteImport } from './routes/blog.what-is-product-sampling'
import { Route as BlogWhatToLookForInAProductSamplingAgencyRouteImport } from './routes/blog.what-to-look-for-in-a-product-sampling-agency'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as WhatWeDoBrandExperienceRouteImport } from './routes/what-we-do.brand-experience'
import { Route as WhatWeDoProductSamplingRouteImport } from './routes/what-we-do.product-sampling'
import { Route as WhatWeDoStaffingRouteImport } from './routes/what-we-do.staffing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCookiePolicyRoute = PrivacyCookiePolicyRouteImport.update({
  id: '/privacy-cookie-policy',
  path: '/privacy-cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiryRoute = ApiEnquiryRouteImport.update({
  id: '/api/enquiry',
  path: '/api/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog20ProductSamplingIdeasRoute =
  Blog20ProductSamplingIdeasRouteImport.update({
    id: '/blog/20-product-sampling-ideas',
    path: '/blog/20-product-sampling-ideas',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhatIsProductSamplingRoute =
  BlogWhatIsProductSamplingRouteImport.update({
    id: '/blog/what-is-product-sampling',
    path: '/blog/what-is-product-sampling',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhatToLookForInAProductSamplingAgencyRoute =
  BlogWhatToLookForInAProductSamplingAgencyRouteImport.update({
    id: '/blog/what-to-look-for-in-a-product-sampling-agency',
    path: '/blog/what-to-look-for-in-a-product-sampling-agency',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoBrandExperienceRoute = WhatWeDoBrandExperienceRouteImport.update({
  id: '/what-we-do/brand-experience',
  path: '/what-we-do/brand-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoProductSamplingRoute = WhatWeDoProductSamplingRouteImport.update({
  id: '/what-we-do/product-sampling',
  path: '/what-we-do/product-sampling',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoStaffingRoute = WhatWeDoStaffingRouteImport.update({
  id: '/what-we-do/staffing',
  path: '/what-we-do/staffing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-cookie-policy': typeof PrivacyCookiePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/enquiry': typeof ApiEnquiryRoute
  '/blog/20-product-sampling-ideas': typeof Blog20ProductSamplingIdeasRoute
  '/blog/what-is-product-sampling': typeof BlogWhatIsProductSamplingRoute
  '/blog/what-to-look-for-in-a-product-sampling-agency': typeof BlogWhatToLookForInAProductSamplingAgencyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/what-we-do/brand-experience': typeof WhatWeDoBrandExperienceRoute
  '/what-we-do/product-sampling': typeof WhatWeDoProductSamplingRoute
  '/what-we-do/staffing': typeof WhatWeDoStaffingRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-cookie-policy': typeof PrivacyCookiePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/enquiry': typeof ApiEnquiryRoute
  '/blog/20-product-sampling-ideas': typeof Blog20ProductSamplingIdeasRoute
  '/blog/what-is-product-sampling': typeof BlogWhatIsProductSamplingRoute
  '/blog/what-to-look-for-in-a-product-sampling-agency': typeof BlogWhatToLookForInAProductSamplingAgencyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/what-we-do/brand-experience': typeof WhatWeDoBrandExperienceRoute
  '/what-we-do/product-sampling': typeof WhatWeDoProductSamplingRoute
  '/what-we-do/staffing': typeof WhatWeDoStaffingRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-cookie-policy': typeof PrivacyCookiePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/enquiry': typeof ApiEnquiryRoute
  '/blog/20-product-sampling-ideas': typeof Blog20ProductSamplingIdeasRoute
  '/blog/what-is-product-sampling': typeof BlogWhatIsProductSamplingRoute
  '/blog/what-to-look-for-in-a-product-sampling-agency': typeof BlogWhatToLookForInAProductSamplingAgencyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/what-we-do/brand-experience': typeof WhatWeDoBrandExperienceRoute
  '/what-we-do/product-sampling': typeof WhatWeDoProductSamplingRoute
  '/what-we-do/staffing': typeof WhatWeDoStaffingRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-cookie-policy'
    | '/sitemap.xml'
    | '/api/enquiry'
    | '/blog/20-product-sampling-ideas'
    | '/blog/what-is-product-sampling'
    | '/blog/what-to-look-for-in-a-product-sampling-agency'
    | '/projects/$slug'
    | '/what-we-do/brand-experience'
    | '/what-we-do/product-sampling'
    | '/what-we-do/staffing'
    | '/blog/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-cookie-policy'
    | '/sitemap.xml'
    | '/api/enquiry'
    | '/blog/20-product-sampling-ideas'
    | '/blog/what-is-product-sampling'
    | '/blog/what-to-look-for-in-a-product-sampling-agency'
    | '/projects/$slug'
    | '/what-we-do/brand-experience'
    | '/what-we-do/product-sampling'
    | '/what-we-do/staffing'
    | '/blog'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-cookie-policy'
    | '/sitemap.xml'
    | '/api/enquiry'
    | '/blog/20-product-sampling-ideas'
    | '/blog/what-is-product-sampling'
    | '/blog/what-to-look-for-in-a-product-sampling-agency'
    | '/projects/$slug'
    | '/what-we-do/brand-experience'
    | '/what-we-do/product-sampling'
    | '/what-we-do/staffing'
    | '/blog/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyCookiePolicyRoute: typeof PrivacyCookiePolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEnquiryRoute: typeof ApiEnquiryRoute
  Blog20ProductSamplingIdeasRoute: typeof Blog20ProductSamplingIdeasRoute
  BlogWhatIsProductSamplingRoute: typeof BlogWhatIsProductSamplingRoute
  BlogWhatToLookForInAProductSamplingAgencyRoute: typeof BlogWhatToLookForInAProductSamplingAgencyRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WhatWeDoBrandExperienceRoute: typeof WhatWeDoBrandExperienceRoute
  WhatWeDoProductSamplingRoute: typeof WhatWeDoProductSamplingRoute
  WhatWeDoStaffingRoute: typeof WhatWeDoStaffingRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-cookie-policy': {
      id: '/privacy-cookie-policy'
      path: '/privacy-cookie-policy'
      fullPath: '/privacy-cookie-policy'
      preLoaderRoute: typeof PrivacyCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiry': {
      id: '/api/enquiry'
      path: '/api/enquiry'
      fullPath: '/api/enquiry'
      preLoaderRoute: typeof ApiEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/20-product-sampling-ideas': {
      id: '/blog/20-product-sampling-ideas'
      path: '/blog/20-product-sampling-ideas'
      fullPath: '/blog/20-product-sampling-ideas'
      preLoaderRoute: typeof Blog20ProductSamplingIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-product-sampling': {
      id: '/blog/what-is-product-sampling'
      path: '/blog/what-is-product-sampling'
      fullPath: '/blog/what-is-product-sampling'
      preLoaderRoute: typeof BlogWhatIsProductSamplingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-to-look-for-in-a-product-sampling-agency': {
      id: '/blog/what-to-look-for-in-a-product-sampling-agency'
      path: '/blog/what-to-look-for-in-a-product-sampling-agency'
      fullPath: '/blog/what-to-look-for-in-a-product-sampling-agency'
      preLoaderRoute: typeof BlogWhatToLookForInAProductSamplingAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/brand-experience': {
      id: '/what-we-do/brand-experience'
      path: '/what-we-do/brand-experience'
      fullPath: '/what-we-do/brand-experience'
      preLoaderRoute: typeof WhatWeDoBrandExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/product-sampling': {
      id: '/what-we-do/product-sampling'
      path: '/what-we-do/product-sampling'
      fullPath: '/what-we-do/product-sampling'
      preLoaderRoute: typeof WhatWeDoProductSamplingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/staffing': {
      id: '/what-we-do/staffing'
      path: '/what-we-do/staffing'
      fullPath: '/what-we-do/staffing'
      preLoaderRoute: typeof WhatWeDoStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyCookiePolicyRoute: PrivacyCookiePolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEnquiryRoute: ApiEnquiryRoute,
  Blog20ProductSamplingIdeasRoute: Blog20ProductSamplingIdeasRoute,
  BlogWhatIsProductSamplingRoute: BlogWhatIsProductSamplingRoute,
  BlogWhatToLookForInAProductSamplingAgencyRoute:
    BlogWhatToLookForInAProductSamplingAgencyRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WhatWeDoBrandExperienceRoute: WhatWeDoBrandExperienceRoute,
  WhatWeDoProductSamplingRoute: WhatWeDoProductSamplingRoute,
  WhatWeDoStaffingRoute: WhatWeDoStaffingRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
